data:extend{
    {
        type = "int-setting",
        name = "cargo-drone-inventory-size",
        setting_type = "startup",
        default_value = 10,
        minimum_value = 1,
        maximum_value = 300,
        order = "a-inventory-a",
    },
    {
        type = "int-setting",
        name = "cargo-drone-fuel-inventory-size",
        setting_type = "startup",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 100,
        order = "a-inventory-b",
    },
    {
        type = "int-setting",
        name = "cargo-drone-burnt-result-inventory-size",
        setting_type = "startup",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 100,
        order = "a-inventory-c",
    },

    {
        type = "int-setting",
        name = "cargo-drone-max-collect-provider-items",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "b-scheduler-a",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-collect-requester-items",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "b-scheduler-b",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-sort-idle-drones",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "b-scheduler-c",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-assign-task-to-non-empty-drones",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "b-scheduler-d",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-processed-item-requests",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "b-scheduler-f",
    },
}
