data:extend{
    {
        type = "int-setting",
        name = "cargo-drone-inventory-size",
        setting_type = "startup",
        default_value = 10,
        minimum_value = 1,
        maximum_value = 300,
        order = "a-inventory-a",
    },
    {
        type = "int-setting",
        name = "cargo-drone-fuel-inventory-size",
        setting_type = "startup",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 100,
        order = "a-inventory-b",
    },
    {
        type = "int-setting",
        name = "cargo-drone-burnt-result-inventory-size",
        setting_type = "startup",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 100,
        order = "a-inventory-c",
    },

    {
        type = "int-setting",
        name = "cargo-drone-stuck-at-refueler-seconds-alert",
        setting_type = "runtime-global",
        default_value = 120,
        minimum_value = 0,
        maximum_value = 3600,
        order = "b-mooring-a",
    },
    {
        type = "int-setting",
        name = "cargo-drone-heuristic-target-count-cost",
        setting_type = "runtime-global",
        default_value = 50,
        minimum_value = 0,
        maximum_value = 10000,
        order = "b-mooring-b",
    },

    {
        type = "int-setting",
        name = "cargo-drone-min-schedule-interval",
        setting_type = "runtime-global",
        default_value = 60,
        minimum_value = 1,
        maximum_value = 3600,
        order = "c-scheduler-a",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-scanned-moorings",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-b",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-sort-idle-drones",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-c",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-collect-provider-items",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-d",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-collect-requester-items",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-e",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-assign-task-to-non-empty-drones",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-f",
    },
    {
        type = "int-setting",
        name = "cargo-drone-max-processed-item-requests",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order = "c-scheduler-g",
    },
}
